// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiouihtvzvpoqzjzzivi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpb3VpaHR2enZwb3F6anp6aXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTU1NDAsImV4cCI6MjA3MTg5MTU0MH0.ASOFnmZwLzMZbGdP4X0wPKo-vhdsmYqfb6neal0CklY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});